# Generated by Django 2.2.6 on 2019-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191109_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepercolaborator',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
