# Generated by Django 2.2.6 on 2019-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191110_2352'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicepercolaborator',
            constraint=models.UniqueConstraint(fields=('service', 'colaborator'), name='colaborator_x_service'),
        ),
    ]
