# Generated by Django 2.2.6 on 2019-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191110_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pet_types',
        ),
        migrations.AddField(
            model_name='servicepercolaborator',
            name='pet_types',
            field=models.ManyToManyField(to='core.TypePet'),
        ),
    ]
