# Generated by Django 2.2.6 on 2019-11-09 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edad', models.PositiveSmallIntegerField()),
                ('pet_image', models.ImageField(upload_to='pets/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TypePet')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('datetime_booking', models.DateTimeField()),
                ('datetime_finally', models.DateTimeField()),
                ('status', models.CharField(choices=[('request', 'Solicitado'), ('accepted', 'Aceptado'), ('waitpayment', 'Esperando pago'), ('rejected', 'Rechazado'), ('inprogress', 'Iniciado'), ('finalized', 'Finalizado')], max_length=255)),
                ('score', models.PositiveSmallIntegerField()),
                ('is_payment', models.BooleanField(blank=True, null=True)),
                ('payment_date', models.DateTimeField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Pet')),
            ],
        ),
    ]
