# Generated by Django 2.2.6 on 2019-11-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191109_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utility',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
