# Generated by Django 2.2.6 on 2019-11-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'Solicitado'), ('accepted', 'Aceptado'), ('waitpayment', 'Esperando pago'), ('rejected', 'Rechazado'), ('expired', 'Expirado'), ('inprogress', 'Iniciado'), ('finalized', 'Finalizado')], max_length=255),
        ),
    ]
