# Generated by Django 2.2.6 on 2019-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20191110_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'Solicitado'), ('accepted', 'Aceptado'), ('waitpayment', 'Esperando pago'), ('rejected', 'Rechazado'), ('expired', 'Expirado'), ('ready', 'Listo para iniciar'), ('inprogress', 'Iniciado'), ('finalized', 'Finalizado')], max_length=255),
        ),
    ]
