# Generated by Django 2.2.6 on 2019-11-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20191116_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_finally',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
