# Generated by Django 2.2.6 on 2019-11-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20191116_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours_contract',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
