# Generated by Django 2.2.6 on 2019-11-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPerson', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('experience', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('qualification', models.IntegerField(default=5)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
